### PR TITLE
fixes #78

### LINKED ISSUE #78: TestExecutionException is never used
It's only used in a test, that seems weird. What's going on?

### PR DESCRIPTION
**Pull request by HellPat**

### CODE REVIEW

File: tests/Variant/CallbackVariantTest.php [hunk 1]
```diff
@@ -34,13 +34,13 @@ public function testRunExecutesCallback()
...
 
     /**
-     * @expectedException \PhpAb\Exception\TestExecutionException
+     * @expectedException \RuntimeException
      */
     public function testRunClosureThrowsException()
     {
         // Arrange
         $variant = new CallbackVariant('name', function () {
-            throw new TestExecutionException();
```
Comment (waltertamboer) [inline tests/Variant/CallbackVariantTest.php:50]: Should TestExecutionException be removed? It's not being used anywhere now.
